### ISSUE TITLE
Theres a uasyncio implementation for esp hardware

### ISSUE THREAD

**Issue by PibePlayer** [danni/uwebsockets#12]
[micropython-async](https://github.com/peterhinch/micropython-async/blob/master/TUTORIAL.md)

**Comment by danni** [comment]
Thanks. Anyone who's interested is welcome to make it work with the uasyncio version of this code. Like so many embedded projects, none of this is maintained now that the device is built :-P

**Comment by iBobik** [comment]
This fork seems to implemented it: https://github.com/RobertBlackhart/uwebsockets
