### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by ricpar123** [danni/uwebsockets#14]
Hi, trying to do the example, I faced with this error, after executing ...'ampy run example/client.py', ..importError: no module named \'logging\'\r\n').

What's wrong?

Thanks
Regards

**Comment by danni** [comment]
You need a version of micropython with `logging`.

**Comment by danni** [comment]
You could also try `micropython-logging` I haven't tried that.

**Comment by ricpar123** [comment]
ahh...ok, thanks!
