### ISSUE TITLE
uwebsockets.client cannot deal with missing port in URL

### ISSUE THREAD

**Issue by Hermann-SW** [danni/uwebsockets#2]
Resolved here:
[https://github.com/Hermann-SW/uwebsockets#example-client-against-wsechowebsocketorg](https://github.com/Hermann-SW/uwebsockets#example-client-against-wsechowebsocketorg)

**Comment by danni** [comment]
Send a pull request?

**Comment by Hermann-SW** [comment]
Thanks, my last pull request in MicroPython area wrt webrepl_client.py got only opposition, that was the reason I raised the issues pointing to solution, and wait for being asked:
[https://github.com/danni/uwebsockets/pull/4](https://github.com/danni/uwebsockets/pull/4)
