### ISSUE TITLE
uwebsockets.client cannot deal with echo.websocket.org websocket upgrade response

### ISSUE THREAD

**Issue by Hermann-SW** [danni/uwebsockets#3]
Resolved here:
[https://github.com/Hermann-SW/uwebsockets#example-client-against-wsechowebsocketorg](https://github.com/Hermann-SW/uwebsockets#example-client-against-wsechowebsocketorg)

**Comment by danni** [comment]
Send a pull request?

**Comment by Hermann-SW** [comment]
[https://github.com/danni/uwebsockets/pull/4](https://github.com/danni/uwebsockets/pull/4)
Thanks for your great repo!
I tried some other MicroPython websocket libraries and they all had issues.
I used your websockets.client to remote control a second ESP-01s module running MicroPython from a first ESP-01s module, via WebREPL!
[https://forum.micropython.org/viewtopic.php?f=2&t=5351&p=30829#p30829](https://forum.micropython.org/viewtopic.php?f=2&t=5351&p=30829#p30829)

**Comment by danni** [comment]
That's actually quite cool. You could probably also build a server. I've been meaning to try bringing back the asyncio branch, which was held up on device support. I've just not needed to program any of these in a while.
